# Test True function

In [2]:
import numpy as np
from sympy import Matrix


K = np.array([[17,17,5],
              [21, 18,21],
              [2,2,19]])

K_1 = np.linalg.inv(K) % 26
# print(K_1)
K_2 = np.array([[4,9,15],
                [15,17,6],
                [24,0,17]])

inv_key = Matrix(K).inv_mod(26)
K_3 = np.array(inv_key).astype(int)

print(f"Key: \n {K}")
print(f"Test First inverse_matrix: \n {np.round(np.dot(K_1, K)) % 26}")
print(f"Test Second inverse_matrix: \n {np.dot(K, K_2) % 26}")
print(f"Test Third inverse_matrix: \n {np.matmul(K, K_3)%26}")
print()
print()

Key: 
 [[17 17  5]
 [21 18 21]
 [ 2  2 19]]
Test First inverse_matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Test Second inverse_matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Test Third inverse_matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]




In [3]:
K = np.array([[17,17,5],
              [21, 18,21],
              [2,2,19]])
H1 = np.array([[15],[0],[24]])
print(np.dot(K, H1)%26)
print(np.dot(K,H1))

[[11]
 [13]
 [18]]
[[375]
 [819]
 [486]]


In [4]:
17*15 + 17*0 + 5*24
21*15 + 18*0 + 21*24
2*15 + 2*0 + 19*24

486

In [5]:
P = np.array([1,2,3]).T
print(P)
C = np.round(np.matmul(K,P) % 26) 
print(C)
P_d = np.matmul(K_3,C) % 26
print(P_d)

[1 2 3]
[14 16 11]
[1 2 3]


# Hill

In [6]:
import numpy as np
import math

def text_2_int(char):
    return ord(char) - ord('A')


def get_Key(input_text):
    # print(len(input_text))
    matrix_size = int(math.sqrt(len(input_text)))
    # print(matrix_size)
    matrix = np.zeros((matrix_size, matrix_size), dtype=int)
    # print(matrix)
    for i in range(matrix_size):
        for j in range(matrix_size):
            char_index = i * matrix_size + j 
            if char_index < len(input_text):
                matrix[i, j] = text_2_int(input_text[char_index])
    return matrix

input_text = "sede"
key_matrix = get_Key(input_text)
print(key_matrix)
inverse_matrix = np.linalg.inv(key_matrix) % 26
print(inverse_matrix)
y = np.array([[1],
              [2],])
print(np.dot(np.dot(inverse_matrix, key_matrix)% 26, y))
print(np.dot(inverse_matrix, np.round(np.dot(key_matrix,y) % 26))%26)


[[50 36]
 [35 36]]
[[ 0.06666667 25.93333333]
 [25.93518519  0.09259259]]
[[1.]
 [2.]]
[[ 1.        ]
 [25.11111111]]


In [7]:
def hill_cipher_encrypt(plain_text, key_matrix):
    plain_text = plain_text.replace(" ", "").upper()
    n = len(plain_text)
    while n % key_matrix.shape[0] != 0:
        plain_text += "X"
        n += 1
    encrypted_text = ""
    for i in range(0, n, key_matrix.shape[0]):
        string = plain_text[i: i+ key_matrix.shape[0]]
        # print(string)
        block = np.array([text_2_int(string[j]) for j in range(len(string))])
        # print(f"Block {int(i/3)}: {block} {block.shape}" )
        encrypted_block = np.round(np.dot(key_matrix,block) % 26) 
        # print(encrypted_block)
        encrypted_text += "".join([chr(c + ord("A")) for c in encrypted_block])
        # print(encrypted_text)
        # print()
    return encrypted_text

def hill_cipher_decrypt(encrypted_text, key_matrix):
    n = len(encrypted_text)
    decrypted_text = ""
    inverse_key = Matrix(key_matrix).inv_mod(26)
    print(inverse_key)
    for i in range(0, n, key_matrix.shape[0]):
        string = encrypted_text[i: i+ key_matrix.shape[0]]
        # print(string)
        block = np.array([text_2_int(string[j]) for j in range(len(string))])
        # print(f"Block {int(i/3)}: {block}" )
        decrypted_block = np.matmul(inverse_key,block) % 26
        # print(decrypted_block)
        decrypted_text += "".join([chr(c + ord("A")) for c in decrypted_block])
        # print(decrypted_text)
        # print()
    return decrypted_text

key_matrix = np.array([[17,17,5],
                       [21,18,21],
                       [2,2,19]])
plain_text = "paymoremoney"
print("PlainText:", plain_text)
encrypted_text = hill_cipher_encrypt(plain_text, key_matrix)
print("EncryptedText:", encrypted_text)
decrypted_text = hill_cipher_decrypt(encrypted_text, key_matrix)
print("DecryptedText:", decrypted_text)


PlainText: paymoremoney
EncryptedText: LNSHDLEWMTRW
Matrix([[4, 9, 15], [15, 17, 6], [24, 0, 17]])
DecryptedText: PAYMOREMONEY


In [9]:
input_text = "GYBNQKURP"
input_text = str(input("Enter your key: "))
key_matrix = get_Key(input_text)
plain_text = "ACTION"
plain_text = str(input("Enter your plain text: "))
print("PlainText:", plain_text)
encrypted_text = hill_cipher_encrypt(plain_text, key_matrix)
print("EncryptedText:", encrypted_text)
decrypted_text = hill_cipher_decrypt(encrypted_text, key_matrix)
print("DecryptedText:", decrypted_text)

PlainText: action
EncryptedText: POHHQV
Matrix([[8, 5, 10], [21, 8, 21], [21, 12, 8]])
DecryptedText: ACTION
