# Test True function

In [25]:
#
import numpy as np
from sympy import Matrix


K = np.array([[17,17,5],
              [21, 18,21],
              [2,2,19]])

K_1 = np.linalg.inv(K) % 26
# print(K_1)
K_2 = np.array([[4,9,15],
                [15,17,6],
                [24,0,17]])

inv_key = Matrix(K).inv_mod(26)
K_3 = np.array(inv_key).astype(int)

print(f"Key: \n {K}")
print(f"Test First inverse_matrix: \n {np.round(np.dot(K_1, K)) % 26}")
print(f"Test Second inverse_matrix: \n {np.dot(K, K_2) % 26}")
print(f"Test Third inverse_matrix: \n {np.matmul(K, K_3)%26}")
print()
print()

Key: 
 [[17 17  5]
 [21 18 21]
 [ 2  2 19]]
Test First inverse_matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Test Second inverse_matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Test Third inverse_matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]




In [30]:
P = np.array([1,2,3]).T
print(P)
C = np.round(np.matmul(K,P) % 26) 
print(C)
P_d = np.matmul(K_3,C) % 26
print(P_d)

[1 2 3]
[14 16 11]
[1 2 3]


# Hill

In [6]:
import numpy as np
import math

def text_2_int(char):
    return ord(char) - ord('A')


def get_Key(input_text):
    # print(len(input_text))
    matrix_size = int(math.sqrt(len(input_text)))
    # print(matrix_size)
    matrix = np.zeros((matrix_size, matrix_size), dtype=int)
    # print(matrix)
    for i in range(matrix_size):
        for j in range(matrix_size):
            char_index = i * matrix_size + j 
            if char_index < len(input_text):
                matrix[i, j] = text_2_int(input_text[char_index])
    return matrix

input_text = "GYBNQKURP"
key_matrix = get_Key(input_text)
print(key_matrix)
inverse_matrix = np.linalg.inv(key_matrix) % 26
print(inverse_matrix)
y = np.array([[1],
              [2],
              [3]])
print(np.dot(np.dot(inverse_matrix, key_matrix)% 26, y))
print(np.dot(inverse_matrix, np.round(np.dot(key_matrix,y) % 26))%26)


[[ 6 24  1]
 [13 16 10]
 [20 17 15]]
[[1.58730159e-01 2.52222222e+01 5.07936508e-01]
 [1.13378685e-02 1.58730159e-01 2.58934240e+01]
 [2.57755102e+01 8.57142857e-01 2.55102041e+01]]
[[1.]
 [2.]
 [3.]]
[[19.57142857]
 [ 1.46938776]
 [ 8.30612245]]


In [39]:
def hill_cipher_encrypt(plain_text, key_matrix):
    plain_text = plain_text.replace(" ", "").upper()
    n = len(plain_text)
    while n % key_matrix.shape[0] != 0:
        plain_text += "X"
        n += 1

    encrypted_text = ""
    for i in range(0, n, key_matrix.shape[0]):
        string = plain_text[i: i+ 3]
        block = np.array([text_2_int(string[j]) for j in range(len(string))])
        # print(f"Block {int(i/3)}: {block} {block.shape}" )
        encrypted_block = np.round(np.dot(key_matrix,block) % 26) 
        # print(encrypted_block)
        encrypted_text += "".join([chr(c + ord("A")) for c in encrypted_block])
        # print(encrypted_text)
        # print()
    return encrypted_text

def hill_cipher_decrypt(encrypted_text, key_matrix):
    n = len(encrypted_text)
    decrypted_text = ""
    inverse_key = Matrix(key_matrix).inv_mod(26)
    for i in range(0, n, key_matrix.shape[0]):
        string = encrypted_text[i: i+ 3]
        # print(string)
        block = np.array([text_2_int(string[j]) for j in range(len(string))])
        # print(f"Block {int(i/3)}: {block}" )
        decrypted_block = np.matmul(inverse_key,block) % 26
        # print(decrypted_block)
        decrypted_text += "".join([chr(c + ord("A")) for c in decrypted_block])
        # print(decrypted_text)
        # print()
    return decrypted_text

key_matrix = np.array([[17,17,5],
                       [21,18,21],
                       [2,2,19]])
plain_text = "paymoremoney"
print("PlainText:", plain_text)
encrypted_text = hill_cipher_encrypt(plain_text, key_matrix)
print("EncryptedText:", encrypted_text)
decrypted_text = hill_cipher_decrypt(encrypted_text, key_matrix)
print("DecryptedText:", decrypted_text)


PlainText: paymoremoney
EncryptedText: LNSHDLEWMTRW
DecryptedText: PAYMOREMONEY


In [40]:
input_text = "GYBNQKURP"
key_matrix = get_Key(input_text)
plain_text = "ACTION"
print("PlainText:", plain_text)
encrypted_text = hill_cipher_encrypt(plain_text, key_matrix)
print("EncryptedText:", encrypted_text)
decrypted_text = hill_cipher_decrypt(encrypted_text, key_matrix)
print("DecryptedText:", decrypted_text)

PlainText: ACTION
EncryptedText: POHHQV
DecryptedText: ACTION
